Repository yvt/openspades, pull requests merged in 2019-05, with the labels that each got.

#830 Display a real progress bar when receiving a map
  OpenSpades.xcodeproj/project.pbxproj
  Resources/Locales/pot/openspades.pot
  Sources/Client/Client.cpp
  Sources/Client/Client.h
  Sources/Client/Client_Draw.cpp
  Sources/Client/GameMap.cpp
  Sources/Client/GameMap.h
  Sources/Client/GameMapLoader.cpp
  Sources/Client/GameMapLoader.h
  Sources/Client/NetClient.cpp
  Sources/Client/NetClient.h
  Sources/Core/IStream.cpp
  Sources/Core/IStream.h
  Sources/Core/PipeStream.cpp
  Sources/Core/PipeStream.h
  Sources/Core/RandomAccessAdaptor.cpp
  Sources/Core/RandomAccessAdaptor.h
  Sources/Core/TMPUtils.h
Labels: enhancement

#836 Little code changes proposal.
  Sources/Core/IStream.cpp
  Sources/Core/IStream.h
  Sources/Core/TargaWriter.cpp
  Sources/Core/ZipFileSystem.cpp
  Sources/Draw/GLImage.cpp
  Sources/Draw/GLModelRenderer.cpp
  Sources/binpack2d/binpack2d.hpp
Labels: PR: refactoring

#833 Use model for block cursor instead of debug lines
  Resources/Models/MapObjects/BlockCursorLine.kv6
  Resources/Models/MapObjects/BlockCursorLine.meta.json
  Resources/Models/MapObjects/BlockCursorSingle.kv6
  Resources/Models/MapObjects/BlockCursorSingle.meta.json
  Resources/mkpak.ps1
  Resources/mkpak.sh
  Sources/Client/Client.cpp
  Sources/Client/Client_Scene.cpp
Labels: PR: improvement
